### PR TITLE
Finished starboard with cache

### PR DESCRIPTION
**Pull request by Jay-Madden**
Finished up starboard that was started by zach. Minimum reactions hardcoded to 3 but per guild setting should be made available, tracked in #234 

CC: @new-zelind for review

### CODE REVIEW

**Review by new-zelind — COMMENTED** [review]
Do you have something to remove starboard entries?

**Comment by Jay-Madden** [comment]
No we dont, it was  a design decision to leave them up no matter what. in the words of korey its a snapshot of the highest total star count for the message not the current count

**Comment by new-zelind** [comment]
Works for me.

**Review by new-zelind — APPROVED** [review]
Starboard code approved.

**Pull request merged**
